-- V2__create_author_table.sql
-- PostgreSQL-compatible migration

-- Note: Flyway connects to a specific database. Avoid CREATE DATABASE / USE statements here.

-- Create the author table. Use SERIAL / IDENTITY for auto-increment in PostgreSQL.
CREATE TABLE IF NOT EXISTS author (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(50),
    last_name VARCHAR(50) NOT NULL,
    date_of_birth DATE,
    year_of_birth INT,
    address VARCHAR(50),

    CONSTRAINT pk_author PRIMARY KEY (id)
);
