-- V3__create_book_table_and_records.sql
-- PostgreSQL-compatible migration

-- Note: Flyway connects to a specific database. Avoid CREATE DATABASE / USE statements here.

-- Create the book table (PostgreSQL syntax). Use IDENTITY for id and rely on FK support.
CREATE TABLE IF NOT EXISTS book (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  author_id INT NOT NULL,
  title VARCHAR(400) NOT NULL,

  CONSTRAINT pk_book PRIMARY KEY (id),
  CONSTRAINT fk_book_author_id FOREIGN KEY (author_id) REFERENCES author(id)
);

-- Insert authors. We'll provide explicit ids or let the DB assign them.
INSERT INTO author (first_name, last_name, date_of_birth, year_of_birth, address) VALUES
  ('George', 'Orwell', '1903-06-25', 1903, NULL),
  ('Paulo', 'Coelho', '1947-08-24', 1947, NULL);

-- Insert books. Use explicit author IDs matching inserted rows above (if IDs were auto-assigned, adjust accordingly).
INSERT INTO book (author_id, title) VALUES (1, '1984');
INSERT INTO book (author_id, title) VALUES (1, 'Animal Farm');
INSERT INTO book (author_id, title) VALUES (2, 'O Alquimista');
INSERT INTO book (author_id, title) VALUES (2, 'Brida');
